apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac
data:
  config.yaml: |
    globals:
      SUPER:
        - SUDO
    adapter:
      mode: postgres
      postgres:
        dsn: "user=aka password=password dbname=aka host=db-postgresql port=5432 sslmode=disable"
