configuration:
  allowPublicLinkCreation: true
  externalHost: aka.devel
  adminGroups:
    - open-source
  oidc:
    scopes:
      - profile
      - email
    existingSecret:
      name: oidc
      issuerKey: OIDC_ISSUER_URL
      clientIdKey: OIDC_CLIENT_ID
      clientSecretKey: OIDC_CLIENT_SECRET
postgresql:
  existingSecret:
    name: postgres-dsn
    key: dsn
api:
  image:
    pullPolicy: Never
ui:
  image:
    tag: main
    pullPolicy: Always
oauth2proxy:
  forceOverrideRedirect: http://localhost:3000/auth/callback
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: iss-kube
  tls:
    - secretName: tls-aka
      hosts:
        - aka.devel