configuration:
  allowPublicLinkCreation: true
  externalHost: aka.devel
  adminGroups:
    - open-source
postgresql:
  existingSecret:
    name: postgres-dsn
    key: dsn
api:
  image:
    pullPolicy: Never
ui:
  image:
    tag: main
    pullPolicy: Always
oauth2proxy:
  forceOverrideRedirect: http://localhost:3000/auth/callback
  env:
    - name: OIDC_OPTIONS_ISSUER_URI
      value: https://gitlab.dcas.dev
    - name: OIDC_OPTIONS_SCOPES
      value: "profile,email"
    - name: OIDC_OPTIONS_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: oidc
          key: OIDC_CLIENT_ID
    - name: OIDC_OPTIONS_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: oidc
          key: OIDC_CLIENT_SECRET
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: iss-kube
  tls:
    - secretName: tls-aka
      hosts:
        - aka.devel