stages:
  - verify
  - test
  - build

include:
  - component: gitlab.dcas.dev/autodevops/components/semgrep@main
  - component: gitlab.dcas.dev/autodevops/components/web-build@main
    inputs:
      project: aka-ui
  - component: gitlab.dcas.dev/autodevops/components/go-test@main
    inputs:
      project: aka-api
  - component: gitlab.dcas.dev/autodevops/components/go-build@main
    inputs:
      project: aka-api
      importPath: cmd/jmp
  - component: gitlab.dcas.dev/autodevops/components/go-build@main
    inputs:
      project: oidc-proxy
      importPath: cmd/oidc-proxy
