stages:
  - verify
  - test
  - build

include:
  - component: gitlab.dcas.dev/autodevops/components/semgrep@main
  - component: gitlab.dcas.dev/autodevops/components/web-build@main
    inputs:
      projects: aka-ui
  - component: gitlab.dcas.dev/autodevops/components/go-test@main
    inputs:
      projects: aka-api
  - component: gitlab.dcas.dev/autodevops/components/go-build@main
    inputs:
      projects: aka-api
      importPath: cmd/jmp
