apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aka.fullname" . }}
data:
  config.yaml: |
    globals:
      SUPER:
        - SUDO
    adapter:
      mode: postgres
      postgres:
        dsn: "$AKA_DSN"
