apiVersion: v1
kind: Service
metadata:
  name: {{ include "aka.fullname" . }}
  labels:
    {{- include "aka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: oauth2-proxy
      protocol: TCP
      name: http
    - port: 81
      targetPort: favicon
      protocol: TCP
      name: http-favicon
  selector:
    {{- include "aka.selectorLabels" . | nindent 4 }}
